- name: Installing remi repo
  ansible.builtin.yum:
    name: remi
    state: installed

- name: Install 
  ansible.builtin.dnf:
    name: '@redis:remi-6.2'
    state: present

- name: updating listen address from 127.0.01 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.01'
    replace: '0.0.0.0'

- name: Enabling and restarting redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
