- name: copying mongo repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongdb.repo

- name: Installing mongo 
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Enabling and starting mongod service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: true

- name: Updating listen address from '127.0.0.1' to '0.0.0.0'
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restarting mongod service
  ansible.builtin.systemd:
    name: mongod
    state: restarted