{
 "title": "RoboShop",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "server up or down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - avg by (name)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)"
    }
   ]
  },
  {
   "title": "systemd",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{exported_name=\"cart.service\",  state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"catalogue.service\",  state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"dispatch.service\",  state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"shipping.service\",  state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"user.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"payment.service\",  state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"nginx.service\",  state=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "memory ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "100 - (node_memory_Cached_bytes+node_memory_Buffers_bytes+node_memory_MemFree_bytes)/ node_memory_MemTotal_bytes * 100"
    }
   ]
  }
 ]
}