

- name: Installing erlang repo and rabbitmq repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash ; curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing erlang
  ansible.builtin.yum:
    name: 
    - erlang
    - rabbitmq-server
    state: installed

- name: enabling and restarting rabbitmq-server service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Adding roboshop user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: 
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  when: roboshop is not defined