- name: Copying Elastic Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Installing Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copying filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Enabling and Restarting Filebeat service
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes