- name: Copying logstash configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restarting logstash server
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Checking logstash is running or not
  ansible.builtin.shell: sleep 60; netstat -lntp | grep 5044