- name: download prometheus node exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true

- name: copying node_exporter service file
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/systemd/node_exporter.service

- name: enabling and starting node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: true
    daemon-reload: true