- name: Importing server file
  ansible.builtin.import_tasks:
    file: server.yml
  when: prometheus_server  #checks whether the variabke is true or false

- name: Importing node exporter file
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: node_exporter 