- name: updating prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: updating alerts configuration file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
    loop: "{{alert_files}}"

- name: restarting prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon-reload: true