- name: Installing prometheus server
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: enabling and restarting prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon-reload: true