
- name: installing maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: roboshop app setup 
  ansible.builtin.import_tasks:
    name: roboshop-app-setup.yml

- name: downloading packages and dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args: 
    chdir: /app
#we have to install maven dependencies on app directory so we used args attribute

- name: schema setup
  ansible.builtin.import_tasks:
    name: schema-setup.yml

- name: SYSTEMD_SETUP
  ansible.builtin.import_tasks:
    name: systemd-setup.yml  