
- name: installing python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: ROBOSHOP_APP_SETUP
  ansible.builtin.import_tasks:
    name: roboshop-app-setup.yml

- name: installing python dependencies 
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6   #here we have to install using paticualar version of pip ie, pip3.6

- name: systemd setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml