groups:
- name: Roboshop
  rules:
# alert rule for service - cart.service  
  {% for component in components %}
  - alert: Service Down alert
    expr: node_systemd_unit_state{exported_name="{{component}}.service",  state="active"} < 1            # in expr: we need to mention the query we run in prometheus/grafana
    for: 30s
    labels:
      severity: critical
      appName: {{component}}     #just adding more notations
    annotations:
      summary: service Down on cart service
  {% endfor %}